# Generated by Django 5.0.1 on 2024-02-11 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Internet', 'Интернет'), ('Culture', 'Культура'), ('Science', 'Наука'), ('Society', 'Общество'), ('Policy', 'Политика'), ('Crime', 'Преступления'), ('Incidents', 'Происшествия'), ('Religion', 'Религия'), ('Sport', 'Спорт'), ('Economy', 'Экономика')], default='Internet', max_length=12, unique=True)),
                ('name_en_us', models.CharField(choices=[('Internet', 'Интернет'), ('Culture', 'Культура'), ('Science', 'Наука'), ('Society', 'Общество'), ('Policy', 'Политика'), ('Crime', 'Преступления'), ('Incidents', 'Происшествия'), ('Religion', 'Религия'), ('Sport', 'Спорт'), ('Economy', 'Экономика')], default='Internet', max_length=12, null=True, unique=True)),
                ('name_ru', models.CharField(choices=[('Internet', 'Интернет'), ('Culture', 'Культура'), ('Science', 'Наука'), ('Society', 'Общество'), ('Policy', 'Политика'), ('Crime', 'Преступления'), ('Incidents', 'Происшествия'), ('Religion', 'Религия'), ('Sport', 'Спорт'), ('Economy', 'Экономика')], default='Internet', max_length=12, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('text', models.TextField()),
                ('text_en_us', models.TextField(null=True)),
                ('text_ru', models.TextField(null=True)),
                ('time_in', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('Article', 'Статья'), ('News', 'Новость')], max_length=12)),
                ('title', models.CharField(max_length=64)),
                ('title_en_us', models.CharField(max_length=64, null=True)),
                ('title_ru', models.CharField(max_length=64, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.author')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('Like', 1), ('Dislike', -1)], default='Like', max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.post')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('text', models.TextField()),
                ('time_in', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.post')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(through='news.PostCategory', to='news.category'),
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='news.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
