# Generated by Django 5.0 on 2024-01-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_boolean_grade_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(choices=[(1, 'Like'), (-1, 'Dislike')], default='Like', max_length=7),
        ),
    ]
